#!/bin/bash
MASTER=$(git config --get hello.master)
ORIGIN=$(git config --get hello.origin)
FEATURE=$(git config --get hello.feature)
# default value
MASTER=${MASTER:=master}
ORIGIN=${ORIGIN:=origin}
# FEATURE=${FEATURE:=feature}

[ -n "$FEATURE" ] && FEATURE="${FEATURE}/$1" || FEATURE="$1"

echo "Switch branch ${ORIGIN}/${MASTER} -> ${FEATURE}"

git branch ${FEATURE} ${ORIGIN}/${MASTER}
git checkout ${FEATURE}
git branch --unset-upstream ${FEATURE}